* An attempt at a Kana input method for Emacs

** Features

- かな入力
- 変換機能 (内蔵の =japanese= 入力と同じ)
- Kで文を平仮名と片假名の間で変換 (内蔵の =japanese= 入力と同じ)

** Issues

- I'm pretty sure this doesn't yet work on an actual JIS keyboard
- I'm not a native Japanese speaker
- The name is maybe not the best?

** Tasks

- Full width quotation with Shift is broken, this might require not relying on quail's keyboard translation
- How do we distinguish between the Yen key and the backslash key?
  - I don't know if this is possible… this would mean we have to contend with using shift-ほ to input ー.
  - shift pipe should still be pipe, not ろ
- Should the ^ key insert へ or を when shifted? Consistency says the former, fcitx5 seems to say the latter the way I configured the layouts…
  - let's check what Windows does.
- Should shift + け insert ゖ? Fcitx5 and mozc says no
  - let's check what Windows does.
- Why does shift + / followed by space trigger 変換 as if we typed う?

** Install

Install this package with eg. Straight:

#+begin_src emacs-lisp
(straight-use-package '(japanese-kana :repo "https://github.com/kisaragi-hiu/emacs-japanese-kana-input"))
#+end_src

Then the input method =japanese-kana= and =japanese-kana-katakana= should both be available without needing further setup.

** License

GPLv3. The key part of Kana-Kanji conversion is also just taken straight from the builtin Japanese input method.
